version: "3"

services:
  api:
    build:
      context: .
      target: fastapi-deploy
    container_name: fastapi-app
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
